name: ACF Test

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: adobecoldfusion/coldfusion2021:2021.0.4
    env:
      acceptEULA: YES
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls /opt/coldfusion/
          ls /opt/coldfusion/cfusion/
          ls /opt/coldfusion/cfusion/bin/
          
          ps -aux
          
          /opt/coldfusion/cfusion/bin/cfcompile.sh -cfruntimeuser root -webroot $GITHUB_WORKSPACE -dir $GITHUB_WORKSPACE
          
